version: '3.8'

volumes:
  pg_data:


services:
  db:
    image: postgres:13.10

    env_file:
      - ./.env
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    
    ports:
      - "8008:8000"

    depends_on:
      - db